---
title: "Emissions"
author: "Alexander Klueber"
date: "11/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(readxl)
library(tibble)
library(lubridate)
library(tidyverse)
```

```{r}
#1. Combining carbon footprint with investments via Ticker

#1.a Load in consolidated datasets
SEC_filings <- read_rds("clean-data/SEC_filings.rds")
CCF_combined <- read_rds("clean-data/ccf_combined.rds")

#1.b Calculate average emissions per company over available data to retain one data point
CCF_average <- CCF_combined %>%
  group_by(Account_Number, Ticker, ISIN) %>%
  summarize(Avg_Scope_1 = mean(Scope_1), Avg_Scope_2 = mean(Scope_2), Avg_Bio = mean(Bio_CO2), Avg_total = mean(Total))%>%
  separate(Ticker, c("Ticker", "Country_code"))
  
View(CCF_average)

glimpse(SEC_filings)
glimpse(CCF_average)



#1. c Emissions owned by HMC per year (skaled to 40 bn)

# Join tables
HMC_CCF <- SEC_filings %>%
        left_join(CCF_average, by = c("Ticker", "Ticker"))

# Scale available weights to 100%

# Identify 


View(HMC_CCF)

HMC_CCF %>%
  filter(is.na(Avg_total))%>%
  view()
  
    
```

