---
title: "3 Output visualizations"
author: "Alexander Klueber"
date: "11/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(hrbrthemes)
library(viridis)
library(janitor)
library(forcats)
library(maps)
library(readxl)
library(tibble)
library(lubridate)
library(tidyverse)
```


```{r}
#A. The data available on the fund

#A. 1 Lack of transparency, what is owned and what is reported in 2019
transparent <- data.frame(
  group = c("Published", "Unpublished"),
  value = c(405098000, 40900000000)
  )

lbls <- transparent$group
pct <- round(transparent$value/sum(transparent$value)*100)
lbls <- paste(lbls, pct) # add percents to labels
lbls <- paste(lbls,"%",sep="") # ad % to labels 
Pie_SEC_share <- pie(transparent$value, labels = lbls, border = "white", col = c("#E69F00", "#999999"), init.angle = 270, main = "HMC publishes ownerhsip for .4 of its 40.9 bn USD assets")


#A. 2 The difference between ownership and endowment payout - financing operations for the prior year

endowment_payout <- data.frame(
  step = c("FY 2019 operating expenses", "Endowment payout", "Harvard endoment, June 30, 2018", "FY 2019 operating expenses", "Endowment payout", "Harvard endoment, June 30, 2018"),
  value = c(3.3, 0, 37.3, 1.9, 1.9, 1.9),
  desc = c("#", "#", "#", "%", "%", "%")
  )

Translate_endowment_payout <- ggplot(endowment_payout, aes(x=step, y=value, group=desc, fill = desc))+
geom_col(position ="stack")


#A. 3 Share of endowment payout per school
Schools_endowment_payout <- read_rds("clean-data/Schools_endowment payout.rds")

myPalette <- RColorBrewer::brewer.pal(5, "Set2") 
lbls <- Schools_endowment_payout$School
pct <- round(Schools_endowment_payout$Share_carbon_ownership*100)
lbls <- paste(lbls, pct) # add percents to labels
lbls <- paste(lbls,"%",sep="") # ad % to labels 
Pie_endowment_payout <- pie(Schools_endowment_payout$Share_carbon_ownership, labels = lbls, border = "white", col = myPalette, main = "Share of endowment payout per school for FY2019 / Share of Corporate Carbon Footprint inhereted from endowment assets")


#A. 4 Number of students per school
Barplot_students <- Schools_endowment_payout %>%
  mutate(name = fct_reorder(School, Student_pop.x)) %>%
  ggplot( aes(x=name, y=Student_pop.x)) +
  geom_bar(stat="identity", fill="#f68060", alpha=.6, width=.4) +
  coord_flip() +
  xlab("") +
  ylab("Students")+
  theme_bw()

dir.create("graphics")
write_rds(Pie_SEC_share, "graphics/Pie_SEC_share.rds", compress = "none")
write_rds(Translate_endowment_payout, "graphics/Translate_endowment_payout.rds", compress = "none")
write_rds(Pie_endowment_payout, "graphics/Pie_endowment_payout.rds", compress = "none")
write_rds(Barplot_students, "graphics/Barplot_students.rds", compress = "none")
```

```{r}
#B. Total emissions owned by the schools over 2014 - 2017 

#B.1 Load in data

CCF_per_school <- read_rds("clean-data/CCF_per_school.rds")

#B.2 Visualize line chart
CCF_per_school %>%
  filter(School == "Total")
  ggplot() +
  aes(x=Year, y=Carbon_footprint_in_MT, group=Schools, color = Schools)



CCF_per_school %>%
  filter(Schools != "Total") %>%
  mutate(Carbon_footprint_in_MT_k=Carbon_footprint_in_MT/1000)%>%
  ggplot() +
  aes(x=Year, y=Carbon_footprint_in_MT_k, group=Schools, color = Schools) +
  geom_line() +
  scale_color_viridis(discrete = TRUE) +
  labs(title = "Carbon footprint 'inherited' from endowment for: : {frame_time}",
       y = "Carbon footprint (in '000 MT)")

?transition
  
#write_rds(Chart_emissions_by_school, "graphics/Chart_emissions_by_school", compress = "none")
```
```{r}

#C. Additional carbon footprint per year inherited from HMC from attending Harvard, set next to average footprint per year in US and global

#write_rds(Chart_emissions_per_student, "graphics/Chart_emissions_per_student", compress = "none")
```
```{r}
#D. Table of largest emitters in Harvard Portfolio

#write_rds(Table_largest_emitters, "graphics/Table_largest_emitters", compress = "none")
```
```{r}
#E. Statistical method: Model development of emissions

#write_rds(Chart_prediction_emissions, "graphics/Chart_prediction_emissions", compress = "none")
```

