---
title: "Final Project Proposal"
author: "Alexander Klueber"
date: "10/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Investing in the future? 

Goal: Visualize carbon footprint and mitigation strategies of companies that major university funds are invested in. Ideally translate personalized specifications (time at school, current department, share of operations financed through endowment, etc.) into cost for a freshman starting in 30 years (the current student's child?).

Note: Assumption that average footprint can be extended across rest of portfolio very likely to become necessary.

So far I have conducted no data manipulation.

1. Dataset 1: Find investments by largest university investment funds / Ivy Leagues

SEC filings of largest university endowments

2. Dataset 2: Split of spending from university investment fund
University websites – web scrapping

3. Dataset 3: CDP database on self-reported CO2-Eq emissions by companies  
Datasets from 2010 - 2018	

The CDP (formerly the Carbon Disclosure Project) is an organisation based in the United Kingdom which supports companies and cities to disclose the environmental impact of major corporations. It aims to make environmental reporting and risk management a business norm, and drive disclosure, insight and action towards a sustainable economy.

The data set includes for more than 2,000 of the biggest companies self-reported information on carbon footprint, low-carbon transformation strategy and organizational manifestations of them from 2010 to 2018. As the data is proprietory I am not uploading a copy of the data to the GitHub repo (agreed with Prof. Kane).
